name: Gradle Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Gradle wrapper executable
        run: |
          ./gradlew --version || echo "No wrapper, using system Gradle"

      - name: Build & Run Tests
        run: ./gradlew test || gradle test
